apiVersion: v1
kind: Service
metadata:
  name: ai-agent-ms-service
spec:
  selector:
    app: ai-agent-ms
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  type: ClusterIP